name: 'Package Info'
description: 'Reads the package.json and exposes info'
branding:
    icon: 'arrow-up'
    color: 'yellow'
inputs:
    path:
        description: 'The path to the package.json'
        required: false
        default: 'package.json'
outputs:
    version:
        description: 'The current package.json version'
runs:
    using: 'node12'
    main: 'index.js'
